### ISSUE TITLE
Line numbers and auto-correction of deprecated elements

### ISSUE THREAD

**Issue by jason-fox** [robander/deprecated-dita#1]
I have integrated your stylesheets into the latest release of my fork of the **DITA Validator for DITA-OT**.

My fork includes the missing "fix" functionality as demoed at DITA-OT day and report and auto-fix capability for reporting on deprecated elements.

You state:
> This DITA-OT plugin helps locate (but not correct) use of deprecated markup

Would you like line number and auto-correction added to that?
* `https://github.com/jason-fox/com.here.validate.svrl/releases`

### Sample output
```console
 ./bin/dita --input  ../deprecated-dita/org.metadita.deprecated/sample/deprecated.ditamap -f svrl

[WARN]  [/topic.dita]
  Line 30: linkpool - [linkpool-collection-type-tree-deprecated] 
The <linkpool> element will no longer support collection-type="tree" in DITA 2.0. Replace the value.
[WARN]  [/topic.dita]
  Line 12: simpletable - [refcols-deprecated] 
<simpletable> elements will no longer support the refcols attribute in DITA 2.0. Delete the attribute.

...etc
No Errors Found 24 Warnings
```
I'm not sure what to do to avoid duplication here - I don't think  a pull request or merge is really appropriate  here, but I wanted to add this as an issue to help sign-post the available options to developers.

**Comment by robander** [comment]
Taking a look at this plug-in today after talking about it at CMS/DITA and realized I missed this notification last year. Not sure what more you've done with it but that all looks pretty cool and I wish I'd been quick to respond. Also not sure what the best option here is but if you've done more work or have any other ideas I'm happy to hear.

**Comment by jason-fox** [comment]
Probably the best idea here is to exchange mutual links in the `README.md` to improve navigation - e.g. 
https://github.com/jason-fox/com.here.validate.svrl/commit/4e3a5e9df94f754000e7ebbab93d57b0e1dfc3d2#diff-04c6e90faac2675aa89e2176d2eec7d8

As I said, I only raised this _"issue-that-isn't-really-an-issue"_ in the first place to increase visibility giving users a chance to find out more about an available mechanism for auto-correction of deprecated elements.

Your plug-in focuses purely on **deprecated** which is great, mine is a broader toolkit including identification and fixing of many other stylistic things. Using it could be an appropriate way of fixing a user's deprecation issues, but `auto-fix` (without modification) may be a sledgehammer. 

So I would suggest keep the two  plug-ins separate and swap links then close this _issue_

**Comment by robander** [comment]
Thanks again - added a link to the readme.
